Repository MacRover/maxwell, pull requests merged in 2025-02, with the labels that each got.

#131 BREAKING: EEPROM Bug
  firmware/STM32 Drivers/AT24C04C/Drivers/AT24C04C/Src/stm32f1xx_at24c04c.c
Labels: bug

#132 RAD Control Refactor
  ros_ws/src/bringup_py/launch/drivetrain.launch.py
  ros_ws/src/rad_control/include/rad_control/rad_calibration_init.hpp
  ros_ws/src/rad_control/include/rad_control/rad_status.hpp
  ros_ws/src/rad_control/launch/rad_status_main.launch.py
  ros_ws/src/rad_control/src/rad_calibration_init.cpp
  ros_ws/src/rad_control/src/rad_status.cpp
Labels: RAD, Drive, Arm, refactor

#137 Fix Rover Dimensions in Kinematics Model + Drive Namespacing
  ros_ws/src/bringup_py/launch/drivetrain.launch.py
  ros_ws/src/drive/drive/drive_controller.py
  ros_ws/src/drive/drive/drive_modules_odom.py
  ros_ws/src/drive/drive/heartbeat.py
  ros_ws/src/drive/drive/keyboard_drive.py
  ros_ws/src/drive/drive/sim_command_converter.py
  ros_ws/src/drive/drive/vesc_controller.py
  ros_ws/src/drive/drive/xbox_drive.py
  ros_ws/src/drive/launch/vesc_status.launch.py
  ros_ws/src/rad_control/launch/rad_status_main.launch.py
  ros_ws/src/rad_control/src/rad_drive_controller.cpp
  ros_ws/src/rad_control/src/rad_status.cpp
  ros_ws/src/rad_control/src/rover_steer_pos.cpp
Labels: bug, refactor
